name = "AbstractIterativeSolvers"
uuid = "625e1fda-64c5-4861-b688-905651d1f470"
authors = ["Tom Trogdon"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
